//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class Outpost
{
	private string name, race;
	private int xLoc, yLoc;
	private int population;
	private City hamlet;

	public Outpost (string n, string r, int x, int y)
	{
		name = n;
		race = r;
		xLoc = x;
		yLoc = y;
		population = 1;
	}

	public void expandCheck()
	{
		if (population >= 10 && hamlet == null) 
		{
			hamlet = new City(name, race, xLoc, yLoc, 1, 1);
		}
	}

	public void addToPopulation()
	{
		if (hamlet == null) 
		{
			population += 1;
		}
	}

	public void setName(string n)
	{
		name = n;
	}

	public string getName()
	{
		return name;
	}

	public string getRace()
	{
		return race;
	}

	public int getPopulation()
	{
		return population;
	}

	public City getCity()
	{
		if (hamlet != null)
			return hamlet;
		else 
		{
			System.Console.WriteLine ("The outpost isn't developed enough to become a city yet.");
			return null;
		}
	}
}


